#!/usr/bin/env bash
#################################################################
# Author : Abner Benedito
# Version: 1.0
# License: 0-BSD
#################################################################

#################################################################
# Configs
#################################################################

case "$BASH_VERSION" in
    [4-9].*) : ;; # pass
    *)
        printf 'ERROR: Bash version >=4.0 required, but you have %s\n' "$BASH_VERSION"
        exit 1
    ;;
esac

#################################################################
# Utils
#################################################################

function __SetConfigs() {
    declare -ig TRUE=0 # exit status for success.
    declare -ig FALSE=1 # exit status for recognized error."
    declare -ig ERROR=2 # exit status for not recognized error."

    declare -Ag BP_ENV[root-path]="$PWD"
    declare -Ag BP_ENV[setup-filename]="setup.sh"
    declare -Ag BP_ENV[setup-file]="${BP_ENV[root-path]}/${BP_ENV[setup-filename]}"
}

function __Message() {
    local content="$*"
    printf '%b\n' "$content" >&2
}

function __FatalError() {
    local errorMessage="$*"
    __Message "\e[1;31mfatal error:\e[m $errorMessage"

    exit $FALSE
}

# shellcheck disable=SC2154,SC1090
function __GetConfigValuesFromSetupFile() {
    source "${BP_ENV[setup-file]}"
    declare -Ag BP_ENV[project-name]="$project_name"
    declare -Ag BP_ENV[project-version]="$version"
    declare -Ag BP_ENV[project-desc]="$description"
    unset name version description

    [[ -z "${BP_ENV[project-name]}" ]] &&
        __FatalError "An error occurred while reading the value of 'project_name' in ${BP_ENV[setup-file]}."

    [[ -z "${BP_ENV[project-version]}" ]] &&
        __FatalError "An error occurred while reading the value of 'version' in ${BP_ENV[setup-file]}."

    [[ -z "${BP_ENV[project-desc]}" ]] &&
        __FatalError "An error occurred while reading the value of 'description' in ${BP_ENV[setup-file]}."
}

function __LoadSetupConfigs() {
    __SetConfigs
    __GetConfigValuesFromSetupFile
    echo ${BP_ENV[project-name]}
    echo ${BP_ENV[project-version]}
    echo ${BP_ENV[project-desc]}
};

#################################################################
# main
#################################################################

function __Main() {
    __LoadSetupConfigs

    exit $TRUE
}; __Main